### ISSUE TITLE
This project is gold

### ISSUE THREAD

**Issue by came** [tylim88/Firelord#15]
I don't know why this project has so few stars and downloads, but for me, it is gold. 
Maybe I am missing something or don't see a catch ...but so far, I think Google should just add it to their firebase-admin library or sponsor it. 
Working with firebase-admin on typescript just drives you crazy, especially when you think withConverter() might be the solution 🙈 

Thanks a lot 
Carsten

**Comment by tylim88** [comment]
thank you

low download probably due to:
1. my English 
2. Most Firebase audience are people that new to web programming, they dont care about deep type safe that much

> Working with firebase-admin on typescript just drives you crazy

I felt the same, I dedicated a year to create Firelord to end this chaos

> especially when you think withConverter() might be the solution

withConverter is a trap, it adds more problems

It has nothing to do with type, it simply converts your data in runtime

**Comment by came** [comment]
I have found it after intense searching here https://medium.com/swlh/using-firestore-with-typescript-65bd2a602945
This link should be everywhere where people search for withConvert() or Firebase Typescript.

It's not my first firebase project, but types were always a hassle. I've spent hours creating and maintaining various types for collections, trying to create a generic solution. Unfortunately, I am not as skilled in typing as you seem to be 😄 

Having no types is a showstopper and a no-go to work with firebase. 
I will spread the link ...the docs are fine. It took me 10min to get to the point and get typing.

Thanks so much
