### ISSUE TITLE
Why the 3 separate codebases for web/admin/react native?

### ISSUE THREAD

**Issue by macksal** [tylim88/Firelord#3]
Firstly, excellent work on this project. I'm CTO of a startup about to use Firestore in our mobile app, and I think I am equally obsessed with type safety as yourself @tylim88 :) I would love to contribute to this project if we end up using it in production.

I'm a bit perplexed about the need for 3 entirely different codebases, because we need consistent type safety across admin/RN (optimistic updates are important and one of our drivers behind choosing Firestore, so I can't rely on only mutating documents in cloud functions).

Is it not possible to share the majority of the code across platforms? [typesaurus](https://github.com/kossnocorp/typesaurus) by @kossnocorp has taken  an "adapter" approach. Would it be possible to define a generic "store" interface, and provide a separate factories to construct a store from an App/Firestore instance from any of the Web/Admin/RN SDKs?

**Comment by tylim88** [comment]
```

**Comment by tylim88** [comment]
> Is it not possible to share the majority of the code across platforms? [typesaurus](https://github.com/kossnocorp/typesaurus) by @kossnocorp has taken an "adapter" approach. Would it be possible to define a generic "store" interface, and provide a separate factories to construct a store from an App/Firestore instance from any of the Web/Admin/RN SDKs?

The reason I create individual repositories is that they need platform-specific type definitions

https://github.com/tylim88/Firelord/blob/main/src/firelordFirestore.ts
https://github.com/tylim88/Firelordrn/blob/main/src/firelordFirestore.ts
https://github.com/tylim88/FirelordJS/blob/main/src/types/firelordFirestore.ts

all the types are very similar, I can create my own type to replace all the files but then the wrapper would be oblivious to any type change of the original library, this may seem trivial as the original library doesn't change much, but this is still a potential point of failure

But that doesn't mean the code is not shareable at all

in fact, most of the types and code can be shared, and it is my plan to refactor them into [firecore](https://www.npmjs.com/package/firecore)

> I'm a bit perplexed about the need for 3 entirely different codebases because we need consistent type safety across admin/RN (optimistic updates are important and one of our drivers behind choosing Firestore, so I can't rely on only mutating documents in cloud functions).

You can share the data type definitions for Firelord with Firelordrn, they use the same type of logic

**The end goal is to be able to share data type definitions amongst web, admin and react-native or any js library in future, they will all use the same type engine**

====================================

currently, the web has two versions, v1 and v0, v0 is compatible with admin and react-native

there is only one version for admin and react native, that is v0

in future, there will be v1 for admin and react-native

v1 is far more powerful and easier to use than v0

v1 also understand better how Firestore works(eg v0 allows you to use `undefined` as data, but undefined is not a valid datatype, misconceptions like this are fixed in v1)

v1 is also heavily tested and is production-ready

===================================

You should use v1, but unfortunately, there will be no v1 for react-native and admin in the near future

the reason I started these projects is I want to distract myself from my real-life problem

some people choose drugs and alcohol, but I choose to code

I am not even a web dev and never work as one, it is just pure passion

Firelord is my proudest creation, it is the only library that is able to expose almost all the original API and provide type safety beyond expectation, nothing comes close to it and I doubt anything will, 

not many people understand its value as you do, for this, you got my thanks

But I am tired, I really need to get out of my current life and put my skill into real work

===================================
so the question is, should you use v0?

you can, I can continue to monkey patch it and even help you with PRs, it is not dark and hopeless

I am still active in open source, just not super active as before

meanwhile, you can take a look at [FireCall](https://github.com/tylim88/FireCall), it standardize error handling and provides type safety for firebase callable functions at both front end and back end
